### ISSUE TITLE
Configure ACA-py via Environment Variables

### ISSUE THREAD

**Issue by Executioner1939** [hyperledger/aries-cloudagent-python#2992]
Hi there,

The documentation states that ACA-py can be configured via Environment Variables and that all command line arguments have an ENV equivalent.

I have converted all my CLI arguments into ConfigMaps and Secrets in Kubernetes and am loading them appropriately, however when starting the instance it has the following error:

`aca-py start: error: argument --admin: expected 2 arguments`

The environment variable is this `ACAPY_ADMIN : 0.0.0.0 11000`.

I got all the environment variable names from [The Arg Parser](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/config/argparse.py)

I start ACA-py in the following manner:

```yaml
      containers:
        - name: acapy
          image: bcgovimages/aries-cloudagent:py36-1.16-1_1.0.0-rc1
          command: ["/bin/bash"]
          args: ["-c", "aca-py start"]
```

I have omitted the rest of the Deployment manifest for brevity.

Am I doing something wrong?
