### ISSUE TITLE
BBS enabled docker image overwrites normal image

### ISSUE THREAD

**Issue by rblaine95** [hyperledger/aries-cloudagent-python#3174]
In the [Enabling BBS Signatures Support](https://aca-py.org/latest/deploying/BBSSignatures/) documentation, it's insinuated that 2 docker images are built and published:
* `aries-cloudagent-python` - no BBS support, `linux/amd64` and `linux/arm64` supported
* `aries-cloudagent-bbs` - BBS support, `linux/amd64` only

However, in the Docker Publish action, the Extended (BBS enabled) image uses the same name and tag as the normal (BBS disabled) image, causing an overwrite as both use the same output of the same `meta` step:
```yaml
      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/aries-cloudagent-python
          tags: |
            type=raw,value=py${{ matrix.python-version }}-${{ inputs.tag || github.event.release.tag_name }}

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: main
          build-args: |
            python_version=${{ matrix.python-version }}
            acapy_version=${{ inputs.tag || github.event.release.tag_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: ${{ env.PLATFORMS }}

      - name: Build and Push extended Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }} # This causes the previous (non-bbs) image to be overwritten
          labels: ${{ steps.meta.outputs.labels }}
          target: main
          build-args: |
            python_version=${{ matrix.python-version }}
            acapy_name=aries-cloudagent-bbs
            acapy_version=${{ inputs.tag || github.event.release.tag_name }}
            acapy_reqs=[askar,bbs,didcommv2]
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          # Because of BBS, only linux/amd64 is supported for the extended image
          # https://github.com/hyperledger/aries-cloudagent-python/issues/2124#issuecomment-2293569659
          platforms: linux/amd64
```

I propose adding a dedicated `meta` step for the Extended (BBS enabled) image:
```yaml
      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/aries-cloudagent-python
          tags: |
            type=raw,value=py${{ matrix.python-version }}-${{ inputs.tag || github.event.release.tag_name }}

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: main
          build-args: |
            python_version=${{ matrix.python-version }}
            acapy_version=${{ inputs.tag || github.event.release.tag_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: ${{ env.PLATFORMS }}

      - name: Setup Image Metadata
        id: meta-bbs
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/aries-cloudagent-bbs
          tags: |
            type=raw,value=py${{ matrix.python-version }}-${{ inputs.tag || github.event.release.tag_name }}

      - name: Build and Push extended Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: ${{ steps.meta-bbs.outputs.tags }}
          labels: ${{ steps.meta-bbs.outputs.labels }}
          target: main
          build-args: |
            python_version=${{ matrix.python-version }}
            acapy_name=aries-cloudagent-bbs
            acapy_version=${{ inputs.tag || github.event.release.tag_name }}
            acapy_reqs=[askar,bbs,didcommv2]
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          # Because of BBS, only linux/amd64 is supported for the extended image
          # https://github.com/hyperledger/aries-cloudagent-python/issues/2124#issuecomment-2293569659
          platforms: linux/amd64
```
This will actually publish the missing `aries-cloudagent-bbs` image referenced in the [documentation](https://aca-py.org/latest/deploying/BBSSignatures/)
