### ISSUE TITLE
Document Mediator functionality

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#910]
We need documentation for the mediator functionality recently added to ACA-Py. Given some of the inherit complexities of running multiple instances of ACA-Py and making sure they are each configured correctly, documenting the configuration and common pitfalls is of particular importance.

**Comment by dbluhm** [comment]
Here are some example configurations that I've used for testing:

#### Alice
```yaml
# General
label: Alice
endpoint: http://localhost:3000
inbound-transport:
  - [http, 0.0.0.0, 3000]
outbound-transport: httpno-ledger: true

# Admin
admin: [0.0.0.0, 3001]
admin-insecure-mode: true

# Connections
debug-connections: true
auto-accept-invites: true
auto-accept-requests: true
connections-invite: true

# Mediation
auto-send-keylist-update-in-requests: true
auto-send-keylist-update-in-create-invitation: true
```

#### Bob
```yaml
# General
label: Bob
endpoint: http://localhost:3004
inbound-transport:
  - [http, 0.0.0.0, 3004]
outbound-transport: http
no-ledger: true

# Admin
admin: [0.0.0.0, 3005]
admin-insecure-mode: true

# Connections
debug-connections: true
auto-accept-invites: true
auto-accept-requests: true
connections-invite: true

# Mediation
auto-send-keylist-update-in-requests: true
auto-send-keylist-update-in-create-invitation: true
```

#### Mediator
```yaml
# General
label: Mediator
endpoint: http://localhost:3002
inbound-transport:
  - [http, 0.0.0.0, 3002]
outbound-transport: http
no-ledger: true

# Admin
admin: [0.0.0.0, 3003]
admin-insecure-mode: true

# Connections
debug-connections: true
connections-invite: true
invite-multi-use: true
auto-accept-invites: true
auto-accept-requests: true

# Mediation
open-mediation: true
auto-send-keylist-update-in-requests: true
auto-send-keylist-update-in-create-invitation: true
```
